import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { DIMENSIONS } from '@/api/constants';
import { scoreBand, bandLabel } from '@/lib/band';
import { formatCount, formatPercent, formatScore } from '@/lib/format';
import { dimensionDetail } from './db';

// A real PDF built with pdf-lib, so the downloaded file actually opens in a
// viewer -- earlier this just wrote text that *started* with "%PDF-1.4",
// which downloads with the right extension but isn't a valid document.

const PAGE_WIDTH = 612; // US Letter, points
const PAGE_HEIGHT = 792;
const MARGIN = 56;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function hex(value) {
  const n = parseInt(value.slice(1), 16);
  return rgb(((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255);
}

// Mirrors the design tokens in styles/index.css, so the report reads like an
// extension of the app rather than a generic PDF.
const COLOR = {
  ink: hex('#16181B'),
  inkMuted: hex('#5B6169'),
  inkFaint: hex('#8B9097'),
  border: hex('#E2E4DF'),
  accent: hex('#0E6E58'),
  healthy: hex('#1F8A55'),
  warn: hex('#C08A1E'),
  critical: hex('#C23B3B'),
};

function bandColor(score) {
  const band = scoreBand(score);
  if (band === 'healthy') return COLOR.healthy;
  if (band === 'needs-attention') return COLOR.warn;
  // A null score (not assessed) must never fall through to the critical-red
  // catch-all -- that would read as "this dimension scored 0", not "we
  // couldn't assess it".
  if (band === 'not-assessed') return COLOR.inkFaint;
  return COLOR.critical;
}

function drawHeader(page, fonts, eyebrow, title) {
  let y = PAGE_HEIGHT - MARGIN;
  page.drawText('DQ ACCELERATOR', {
    x: MARGIN,
    y,
    size: 9,
    font: fonts.bold,
    color: COLOR.accent,
  });
  y -= 22;
  page.drawText(title, { x: MARGIN, y, size: 19, font: fonts.bold, color: COLOR.ink });
  y -= 16;
  page.drawText(eyebrow, { x: MARGIN, y, size: 10, font: fonts.regular, color: COLOR.inkMuted });
  y -= 12;
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color: COLOR.border,
  });
  return y - 26;
}

function drawFooter(page, fonts, pageLabel) {
  const note = 'Generated by DQ Accelerator · mock report for local development';
  page.drawText(note, { x: MARGIN, y: 32, size: 8, font: fonts.regular, color: COLOR.inkFaint });
  const width = fonts.regular.widthOfTextAtSize(pageLabel, 8);
  page.drawText(pageLabel, {
    x: PAGE_WIDTH - MARGIN - width,
    y: 32,
    size: 8,
    font: fonts.regular,
    color: COLOR.inkFaint,
  });
}

// A minimal table renderer: a shaded header row, one line of text per cell,
// a hairline under each row. Good enough for a handful of short rows -- not
// meant to wrap or paginate.
function drawTable(page, fonts, startY, columns, rows, cellColorAt) {
  const rowHeight = 24;
  let y = startY;

  page.drawRectangle({
    x: MARGIN,
    y: y - rowHeight + 7,
    width: CONTENT_WIDTH,
    height: rowHeight,
    color: COLOR.border,
    opacity: 0.4,
  });
  let x = MARGIN;
  columns.forEach(({ label, width }) => {
    page.drawText(label, {
      x: x + 10,
      y: y - rowHeight + 15,
      size: 9,
      font: fonts.bold,
      color: COLOR.inkMuted,
    });
    x += width;
  });
  y -= rowHeight;

  rows.forEach((row, rowIndex) => {
    x = MARGIN;
    row.forEach((cell, colIndex) => {
      page.drawText(String(cell), {
        x: x + 10,
        y: y - rowHeight + 15,
        size: 9.5,
        font: colIndex === 0 ? fonts.regular : fonts.mono,
        color: cellColorAt?.(rowIndex, colIndex) ?? COLOR.ink,
      });
      x += columns[colIndex].width;
    });
    page.drawLine({
      start: { x: MARGIN, y: y - rowHeight },
      end: { x: MARGIN + CONTENT_WIDTH, y: y - rowHeight },
      thickness: 0.5,
      color: COLOR.border,
    });
    y -= rowHeight;
  });

  return y - 16;
}

function drawOverviewPage(pdf, fonts, run, isInDepth, pageCount) {
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = drawHeader(
    page,
    fonts,
    isInDepth ? 'In-depth analysis' : 'Summary report',
    'Data quality report',
  );

  page.drawText(run.file, { x: MARGIN, y, size: 13, font: fonts.mono, color: COLOR.ink });
  y -= 16;
  page.drawText(`Run ${run.id} · generated ${new Date().toLocaleString()}`, {
    x: MARGIN,
    y,
    size: 9,
    font: fonts.regular,
    color: COLOR.inkFaint,
  });
  y -= 44;

  page.drawText('Overall score', {
    x: MARGIN,
    y,
    size: 9,
    font: fonts.regular,
    color: COLOR.inkFaint,
  });
  page.drawText(`Records ${formatCount(run.records)}`, {
    x: MARGIN + 200,
    y,
    size: 9,
    font: fonts.regular,
    color: COLOR.inkFaint,
  });
  const cdeLabel =
    typeof run.columns === 'number'
      ? `CDEs ${formatCount(run.cdes)} of ${formatCount(run.columns)}`
      : `CDEs ${formatCount(run.cdes)}`;
  page.drawText(cdeLabel, {
    x: MARGIN + 360,
    y,
    size: 9,
    font: fonts.regular,
    color: COLOR.inkFaint,
  });
  y -= 16;

  if (run.sampled) {
    page.drawText(
      `Sampled: ${formatCount(run.sampledRows)} of ${formatCount(run.records)} rows assessed. ` +
        'Scores are statistically representative, not an exact count.',
      { x: MARGIN, y, size: 8, font: fonts.regular, color: COLOR.inkFaint, maxWidth: CONTENT_WIDTH },
    );
    y -= 14;
  }

  y -= 28;

  page.drawText(formatScore(run.overall), {
    x: MARGIN,
    y,
    size: 34,
    font: fonts.bold,
    color: bandColor(run.overall),
  });
  page.drawText(bandLabel(run.overall), {
    x: MARGIN + 110,
    y: y + 10,
    size: 12,
    font: fonts.bold,
    color: bandColor(run.overall),
  });
  y -= 56;

  page.drawText('Dimensions', { x: MARGIN, y, size: 12, font: fonts.bold, color: COLOR.ink });
  y -= 22;

  drawTable(
    page,
    fonts,
    y,
    [
      { label: 'Dimension', width: 240 },
      { label: 'Score', width: 100 },
      { label: 'Band', width: CONTENT_WIDTH - 340 },
    ],
    DIMENSIONS.map((dimension) => {
      const score = run.scores[dimension.key];
      return [dimension.label, formatScore(score), bandLabel(score)];
    }),
    (rowIndex, colIndex) => {
      if (colIndex === 0) return COLOR.ink;
      const score = run.scores[DIMENSIONS[rowIndex].key];
      return bandColor(score);
    },
  );

  drawFooter(page, fonts, `Page 1 of ${pageCount}`);
}

function drawDimensionPage(pdf, fonts, run, dimension, pageNumber, pageCount) {
  const page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const score = run.scores[dimension.key];
  let y = drawHeader(
    page,
    fonts,
    `Score ${formatScore(score)} · ${bandLabel(score)}`,
    dimension.label,
  );

  const detail = dimensionDetail(run, dimension.key);

  // Not assessed: say so, rather than rendering an empty rules table.
  if (detail.score === null) {
    page.drawText(
      detail.notAssessedReason ?? 'There was not enough information in this file to assess this dimension.',
      { x: MARGIN, y, size: 11, font: fonts.regular, color: COLOR.inkMuted, maxWidth: CONTENT_WIDTH },
    );
    drawFooter(page, fonts, `Page ${pageNumber} of ${pageCount}`);
    return;
  }

  page.drawText('Rules applied', { x: MARGIN, y, size: 12, font: fonts.bold, color: COLOR.ink });
  y -= 22;

  const { rules } = detail;

  drawTable(
    page,
    fonts,
    y,
    [
      { label: 'Rule', width: 260 },
      { label: 'ID', width: 100 },
      { label: 'Pass rate', width: CONTENT_WIDTH - 360 },
    ],
    rules.map((rule) => [rule.name, rule.id, formatPercent(rule.passRate)]),
    (rowIndex, colIndex) => (colIndex === 2 ? bandColor(rules[rowIndex].passRate * 100) : COLOR.ink),
  );

  drawFooter(page, fonts, `Page ${pageNumber} of ${pageCount}`);
}

export async function buildReportPdf(run, type) {
  const isInDepth = type === 'in-depth';
  const pageCount = isInDepth ? DIMENSIONS.length + 1 : 1;

  const pdf = await PDFDocument.create();
  pdf.setTitle(`${run.file} — ${isInDepth ? 'In-depth' : 'Summary'} report`);
  pdf.setProducer('DQ Accelerator (mock)');

  const fonts = {
    regular: await pdf.embedFont(StandardFonts.Helvetica),
    bold: await pdf.embedFont(StandardFonts.HelveticaBold),
    mono: await pdf.embedFont(StandardFonts.Courier),
  };

  drawOverviewPage(pdf, fonts, run, isInDepth, pageCount);

  if (isInDepth) {
    DIMENSIONS.forEach((dimension, i) => {
      drawDimensionPage(pdf, fonts, run, dimension, i + 2, pageCount);
    });
  }

  return pdf.save();
}
